### ISSUE TITLE
Bug 反馈：观看状态文本错误

### ISSUE THREAD

**Issue by SamToki** [xiaoyvyv/bangumi#13]
条目页面（动画、音乐等）中的观看状态人数统计，人数与状态不对应。拿某个具体的条目举例：

网页上显示
813人想看 / 56人看过 / 2309人在看 / 24人搁置 / 14人抛弃

App 上显示
813人想看 / 24人看过 / 56人在看 / 2309人搁置 / 14人抛弃

（v1.0.3）

**Comment by xiaoyvyv** [comment]
fixed
