### ISSUE TITLE
【建议】追番进度那里能批量选择剧集

### ISSUE THREAD

**Issue by leowalk0613** [xiaoyvyv/bangumi#14]
一集一集的点看过也太痛苦了，有蛮多作品我是短时间一口气补完再去bgm标记的。类似chiikawa这种短动画我一般都是囤十集看的……

**Comment by SamToki** [comment]
官方 web 版与这个 app 的追番进度页面都支持「看到」功能…将某集标为「看到」，之前的所有集数就会自动完成

**Comment by xiaoyvyv** [comment]
1.0.3 追番进度支持【看到】
