### ISSUE TITLE
两个小建议：动态图标和内嵌链接

### ISSUE THREAD

**Issue by AiraNadih** [xiaoyvyv/bangumi#15]
我非常欣赏这款 APP 的设计和体验，对此表示由衷的喜爱。在此基础上，我有两点小建议，希望能进一步提升使用体验：

1. 动态图标支持：鉴于 APP 已经实现了动态主题的功能，能否考虑让 APP 图标也支持动态调整（莫奈取色），以达到界面风格的完全统一。
2. 站内链接处理：对于 bgm.tv 和 bangumi.tv 的链接，能否实现通过此 APP 打开，而非跳转至外部浏览器？具体点来说，例如我在其他 APP 中点击链接后，希望能自动跳转到此 APP。

期望这些建议能够得到考虑，并继续优化这款出色的 APP。

**Comment by AiraNadih** [comment]
> 第一点可以，第二点目前无法实现，关联跳转需要在域名下创建文件验证包名签名才行

第二点具体要如何实现我不了解。我之前用的是 czy0729 基于 react-native 开发的客户端，那个是支持关联跳转的。或许有能借鉴的地方？

**Comment by txyyh** [comment]
> 第一点可以，第二点目前无法实现，关联跳转需要在域名下创建文件验证包名签名才行

如果想要让 Android 自动给你启用，才需要在对应域名下放置验证文件。
如果仅仅只是添加关联跳转，让用户手动启用，那是不需要这步的

https://developer.android.com/training/app-links?hl=zh-cn#android-app-links
