### ISSUE TITLE
[BUG] 楼中楼评论贴贴点击逻辑

### ISSUE THREAD

**Issue by AiraNadih** [xiaoyvyv/bangumi#16]
遇到楼中楼评论，点击贴贴时，并不能被正确处理。例如点击已有的 “+1” ，生效的对象似乎是层主的贴。

**Comment by AiraNadih** [comment]
如图： ![ezgif-4-ebbfed2ad2](https://github.com/xiaoyvyv/bangumi/assets/128119996/4200f030-04f8-4fb3-a5e9-b4f6cbd23400)

**Comment by SamToki** [comment]
我之前回复楼中楼时也遇到过，然后赶紧删除了回复，但忘记反馈了
