### ISSUE TITLE
[BUG] 部分图片无法正常加载

### ISSUE THREAD

**Issue by AiraNadih** [xiaoyvyv/bangumi#17]
例如这集讨论贴中的 [#22](https://bangumi.tv/ep/1253355#post_1465857) ，如果通过外部浏览器打开，是可以正常加载出来的。

**Comment by AiraNadih** [comment]
另外，希望在右上角的 “三点” 下拉菜单里加上刷新的操作。

**Comment by AiraNadih** [comment]
似乎只是梯子当时抽风了。不过希望后续能加个占位用于表示某一个评论里带图片，并且能够在加载失败的情况下点击后重新加载。

**Comment by xiaoyvyv** [comment]
这个可能是他们的图床国内访问不了

**Comment by AiraNadih** [comment]
> 不过希望后续能加个占位用于表示某一个评论里带图片，并且能够在加载失败的情况下点击后重新加载。

这个会考虑嘛？
