### ISSUE TITLE
每日放送中无封面的条目会加载到其他作品的封面

### ISSUE THREAD

**Issue by Destiny4073** [xiaoyvyv/bangumi#18]
![Screenshot_20240204_055800](https://github.com/xiaoyvyv/bangumi/assets/79623851/76c1bbe0-b707-46a3-a892-8ed36ca616b2)
![Screenshot_20240204_055933](https://github.com/xiaoyvyv/bangumi/assets/79623851/72264b66-e7a0-4469-abe2-d76d565381ae)

**Comment by xiaoyvyv** [comment]
fixed
