### ISSUE TITLE
[BUG] 追番进度页面，点格子逻辑错误

### ISSUE THREAD

**Issue by AiraNadih** [xiaoyvyv/bangumi#19]
我先点击“看过”了迷宫饭的第 5 集，然后页面自动刷新了，接着就发生了如下图所示的情况：

![ezgif-3-745e4a547b](https://github.com/xiaoyvyv/bangumi/assets/128119996/b4d6fa2a-194b-4ec7-855b-72af6da0743d)

**Comment by AiraNadih** [comment]
我推测是这里的页面元素绑定没有同步？

**Comment by xiaoyvyv** [comment]
action 的包已经修复
