### ISSUE TITLE
[BUG] 搜索角色时点击跳转逻辑不对

### ISSUE THREAD

**Issue by AiraNadih** [xiaoyvyv/bangumi#22]
搜索人物-全部，如果是虚拟角色，点击后的链接路径应该是 character 而不是 person 。

![Screenshot_2024-02-16-20-04-53-174_com xiaoyv bangumi](https://github.com/xiaoyvyv/bangumi/assets/128119996/9521f694-43d7-444b-ba45-679823f178ac)
![Screenshot_2024-02-16-20-04-57-444_com xiaoyv bangumi](https://github.com/xiaoyvyv/bangumi/assets/128119996/b5c4b056-6d45-4e40-ba45-2d3fe57f7baf)

**Comment by xiaoyvyv** [comment]
action 包已修复
