### ISSUE TITLE
增加評分介面

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#25]
如圖希望能增加條目的評分![Screenshot_2024-03-14-04-12-22-352_com.xiaoyv.bangumi.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/56c2dd42-fe13-400a-bf24-c34a8bf9d978)

**Comment by xiaoyvyv** [comment]
github action 里面的版本已经有评分了

**Comment by NeKoOuO** [comment]
> github action 里面的版本已经有评分了

Emm可能是我沒表達清楚 我的意思是增加顯示條目的評分在上面 就是 6.7星 7.3星.....這樣
