### ISSUE TITLE
在看/看過的顏色區分

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#27]
希望在看/看過兩個的顏色能別一樣 ![Screenshot_2024-03-14-18-42-18-126_com.xiaoyv.bangumi.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/c339cc86-c019-4ada-8d35-b365e52c1208)

**Comment by xiaoyvyv** [comment]
FIX
