### ISSUE TITLE
增加進度管理“遊戲”條目

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#33]
目前只有三個 希望遊戲也能點格子![Screenshot_2024-03-14-20-17-30-919_com.xiaoyv.bangumi.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/f3ae2635-0717-48ec-bcd7-063fefb95840)

**Comment by xiaoyvyv** [comment]
官网不支持

**Comment by NeKoOuO** [comment]
> 官网不支持

沒辦法只顯示能改狀態嗎？（想玩/在玩/玩過）
