### ISSUE TITLE
一些Bug和建议

### ISSUE THREAD

**Issue by Auroradanica** [xiaoyvyv/bangumi#38]
· 全屏显示问题：
![IMG_20240324_094006](https://github.com/xiaoyvyv/bangumi/assets/87475428/151f4fe7-b96e-46f0-90c4-753c592ec680)
这个界面对于刘海屏的手机上面的菜单栏触摸会有点困难，能不能向下调一点
· 回复问题：
![Screenshot_2024-03-24-09-35-08-209_com xiaoyv ban](https://github.com/xiaoyvyv/bangumi/assets/87475428/1e1df01c-bc5d-421d-a409-d31353ff127b)
![Screenshot_2024-03-24-09-35-12-504_com xiaoyv ban](https://github.com/xiaoyvyv/bangumi/assets/87475428/a2d181fd-07a0-42a3-a713-8ecd5d676e58)
回复时下面的回复键不会随输入法弹起来
· 一点建议：
话题文章能否支持自由复制
文章中自动识别链接且可以设置在默认浏览器打开
感谢!

**Comment by xiaoyvyv** [comment]
你这个手机安卓系统版本号是多少？

**Comment by Auroradanica** [comment]
> 你这个手机安卓系统版本号是多少？

安卓10

**Comment by xiaoyvyv** [comment]
action 版本已修复
