### ISSUE TITLE
增加連結跳轉應用

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#40]
如下圖所示 Android 12的功能
![Screenshot_2024-03-26-09-42-03-841_com.android.settings.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/388ac05b-79ca-4830-8916-c7253a187472)

**Comment by xiaoyvyv** [comment]
https://github.com/xiaoyvyv/bangumi/actions/runs/8434517683

**Comment by NeKoOuO** [comment]
高產🥰
