### ISSUE TITLE
詳情的點擊邏輯問題

### ISSUE THREAD

**Issue by NeKoOuO** [xiaoyvyv/bangumi#41]
點擊圖中綠色的人物照邏輯應該跳轉人物頁面
但是實際上不管點哪裡都是到二級菜單（跟點更多跳轉是一樣的）
建議把點擊改成人物跳轉
![IMG_20240326_095444.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/e544e4dd-cd91-4bfb-9479-8695568d44c8)

**Comment by xiaoyvyv** [comment]
这里为了优化渲染速度，详情页都统一跳二级页面处理的点击
