### ISSUE TITLE
有关 strings.xml

### ISSUE THREAD

**Issue by david082321** [xiaoyvyv/bangumi#43]
请问能否加入繁体中文语言？

大概把 \*.kt 和 res/layout/\*.xml 里面的字串，移到 res/values/strings.xml 这样才方便翻译

**Comment by NeKoOuO** [comment]
我覺得用https://github.com/BYVoid/OpenCC
是個不錯的選擇

**Comment by xiaoyvyv** [comment]
多语言翻译文档，可以在这里面贡献添加繁体的内容

**Comment by NeKoOuO** [comment]
能給 XML 或JSON 嗎 這個不太好編輯

**Comment by xiaoyvyv** [comment]
这个用QQ或者微信登录一下腾讯文档，打开就可以编辑了

**Comment by NeKoOuO** [comment]
我沒有這些東東..

**Comment by david082321** [comment]
> 多语言翻译文档，可以在这里面贡献添加繁体的内容
> 
> https://docs.qq.com/sheet/DYk9hdG92dFVtTFlt?tab=koxolo

谢谢，已完成

**Comment by NeKoOuO** [comment]
@david082321 感謝！翻譯的很完整
