### ISSUE TITLE
收藏页面内容可否设置成显示全部

### ISSUE THREAD

**Issue by hsiayuchih** [xiaoyvyv/bangumi#56]
收藏界面可否像网页端一样把动画、书籍、游戏之类的内容全部在一个页面展示出来，现阶段是只展示一个类别的内容，如果要管理其他的内容还需要去右上角切换，每次都要这样操作下还是比较繁琐的，具体样式见下图：
**另一款APP**
![1](https://github.com/xiaoyvyv/bangumi/assets/21278771/5fe1cd8c-d86a-474e-b6b8-1f4bc0afa095)
**web端**
![QQ截图20240425110131](https://github.com/xiaoyvyv/bangumi/assets/21278771/4ce0401c-cac6-44d2-9118-e3359de4f681)
![2](https://github.com/xiaoyvyv/bangumi/assets/21278771/5c4b1a92-5aca-41c7-8190-459eca7c4eb3)

**Comment by xiaoyvyv** [comment]
你说的是追番进度页面，你可以自己在设置页调整
