### ISSUE TITLE
上架F-Droid

### ISSUE THREAD

**Issue by goddaneel** [xiaoyvyv/bangumi#76]
如题，请问是否可以上架 F-Droid 或者 IzzyonDroid。

**Comment by goddaneel** [comment]
如果可以的话，我可以代为提交申请收录的issue


F-Droid
https://gitlab.com/fdroid/rfp/-/issues

IzzyOnDroid
https://gitlab.com/IzzyOnDroid/repo/-/issues

**Comment by xiaoyvyv** [comment]
目前项目引用了一些第三方的SDK或SO，不在F-Droid协议内，暂时不打算上

**Comment by goddaneel** [comment]
如果仅仅是私有组件问题的话，可以考虑 izzyondroid，该存储库要求较为宽松。

当然，具体如何选择，我无权干涉。
